local colors = require("base46").get_theme_tb "base_30"

return {
  DevIconC = { fg = colors.blue },
  DevIconCss = { fg = colors.blue },
  DevIconDeb = { fg = colors.cyan },
  DevIconDockerfile = { fg = colors.cyan },
  DevIconHtml = { fg = colors.baby_pink },
  DevIconJpeg = { fg = colors.dark_purple },
  DevIconJpg = { fg = colors.dark_purple },
  DevIconJs = { fg = colors.sun },
  DevIconJson = { fg = colors.sun },
  DevIconKt = { fg = colors.orange },
  DevIconLock = { fg = colors.red },
  DevIconLua = { fg = colors.blue },
  DevIconMp3 = { fg = colors.white },
  DevIconMp4 = { fg = colors.white },
  DevIconOut = { fg = colors.white },
  DevIconPng = { fg = colors.dark_purple },
  DevIconPy = { fg = colors.cyan },
  DevIconToml = { fg = colors.blue },
  DevIconTs = { fg = colors.teal },
  DevIconTtf = { fg = colors.white },
  DevIconRb = { fg = colors.pink },
  DevIconRpm = { fg = colors.orange },
  DevIconVue = { fg = colors.vibrant_green },
  DevIconWoff = { fg = colors.white },
  DevIconWoff2 = { fg = colors.white },
  DevIconXz = { fg = colors.sun },
  DevIconZip = { fg = colors.sun },
  DevIconZig = { fg = colors.orange },
  DevIconMd = { fg = colors.blue },
  DevIconTSX = { fg = colors.blue },
  DevIconJSX = { fg = colors.blue },
  DevIconSvelte = { fg = colors.red },
  DevIconJava = { fg = colors.orange },
  DevIconDart = { fg = colors.cyan },
}
