---@meta

---@class NvConfig
---@field base46 NvBase46Config
---@field ui NvUIConfig

---@class NvBase46Config
---@field theme Chad46ThemeName
---@field transparency boolean
---@field hl_add HLTable
---@field hl_override HLTable
---@field changed_themes table<string, any>

---@class NvUIConfig
---@field cmp { style: string }
---@field telescope { style: string }
---@field statusline { enabled: boolean }

---@class Chad46Config
---@field transparency? boolean
---@field changed_themes? table<string, { base_30?: Base30Table, base_16?: Base16Table, polish_hl?: table<string, HLTable> }>
---@field hl_override? table<string, HLTable>
---@field hl_add? HLTable
---@field statusline? StatuslineConfig
---@field cmp? CmpConfig
---@field integrations? IntegrationsConfig

---@class CmpConfig
---@field style? '"default"'|'"atom"'|'"atom_colored"'|'"flat_light"'|'"flat_dark"'

---@class StatuslineConfig
---@field nvchad_stl? boolean Enable nvchad native statusline
---@field theme? string nvchad_stl: "default"/"minimal"/"vscode"/"vscode_colored"; lualine: "default"/"flat_light"/"flat_dark"/"atom"/"atom_colored"
---@field styles? table<string, fun(): table>
---@field separator_style? '"default"'|'"round"'|'"block"'|'"arrow"'
---@field ignore_focus? string[] Filetypes to hide statusline
---@field order? string[] Custom nvchad_stl component order
---@field modules? table<string, function> Custom nvchad_stl component modules
---@field refresh_interval? number nvchad_stl periodic refresh in ms
---@field section_separators? { left: string, right: string }
---@field component_separators? { left: string, right: string }

---@class IntegrationsConfig
---@field alpha? boolean
---@field avante? boolean
---@field blankline? boolean
---@field blink? boolean
---@field ["blink-pair"]? boolean
---@field bufferline? boolean
---@field cmp? boolean
---@field codeactionmenu? boolean
---@field dap? boolean
---@field devicons? boolean
---@field diffview? boolean
---@field edgy? boolean
---@field flash? boolean
---@field git? boolean
---@field ["git-conflict"]? boolean
---@field gitsigns? boolean
---@field grug_far? boolean
---@field hop? boolean
---@field leap? boolean
---@field lsp? boolean
---@field lspsaga? boolean
---@field markview? boolean
---@field mason? boolean
---@field ["mini-tabline"]? boolean
---@field navic? boolean
---@field neogit? boolean
---@field noice? boolean
---@field notify? boolean
---@field nvimtree? boolean
---@field nvshades? boolean
---@field orgmode? boolean
---@field rainbowdelimiters? boolean
---@field ["render-markdown"]? boolean
---@field semantic_tokens? boolean
---@field snacks? boolean
---@field telescope? boolean
---@field ["tiny-inline-diagnostic"]? boolean
---@field todo? boolean
---@field treesitter? boolean
---@field trouble? boolean
---@field ["vim-illuminate"]? boolean
---@field whichkey? boolean
