local M = {}
function M.get_theme()
  local c = require("chad46").get_theme_tb("base_30")
  return {
    fill = { bg = c.one_bg2 },
    background = { fg = c.grey_fg, bg = c.one_bg },
    buffer = { fg = c.light_grey },
    buffer_selected = { fg = c.white, bg = c.one_bg },
    buffer_visible = { fg = c.light_grey },
    tab = { fg = c.light_grey },
    tab_selected = { fg = c.black, bg = c.blue },
    duplicate_selected = { fg = c.grey_fg, bg = c.one_bg },
    duplicate_visible = { fg = c.grey_fg },
    duplicate = { fg = c.grey_fg },
    modified_selected = { fg = c.yellow, bg = c.one_bg },
    modified_visible = { fg = c.yellow },
    modified = { fg = c.yellow },
    separator_selected = { fg = c.line, bg = c.one_bg },
    separator_visible = { fg = c.line },
    pick_selected = { fg = c.blue, bg = c.one_bg },
    pick_visible = { fg = c.blue },
    pick = { fg = c.blue },
    close_button_selected = { fg = c.grey_fg, bg = c.one_bg },
    close_button_visible = { fg = c.grey_fg },
    close_button = { fg = c.grey_fg },
    diagnostic_selected = { fg = c.red, bg = c.one_bg },
    diagnostic_visible = { fg = c.red },
    diagnostic = { fg = c.red },
    error_selected = { fg = c.red, bg = c.one_bg },
    error_visible = { fg = c.red },
    error = { fg = c.red },
    error_diagnostic_selected = { fg = c.red, bg = c.one_bg },
    error_diagnostic_visible = { fg = c.red },
    error_diagnostic = { fg = c.red },
    warning_selected = { fg = c.yellow, bg = c.one_bg },
    warning_visible = { fg = c.yellow },
    warning = { fg = c.yellow },
    warning_diagnostic_selected = { fg = c.yellow, bg = c.one_bg },
    warning_diagnostic_visible = { fg = c.yellow },
    warning_diagnostic = { fg = c.yellow },
    info_selected = { fg = c.blue, bg = c.one_bg },
    info_visible = { fg = c.blue },
    info = { fg = c.blue },
    info_diagnostic_selected = { fg = c.blue, bg = c.one_bg },
    info_diagnostic_visible = { fg = c.blue },
    info_diagnostic = { fg = c.blue },
    hint_selected = { fg = c.teal, bg = c.one_bg },
    hint_visible = { fg = c.teal },
    hint = { fg = c.teal },
    hint_diagnostic_selected = { fg = c.teal, bg = c.one_bg },
    hint_diagnostic_visible = { fg = c.teal },
    hint_diagnostic = { fg = c.teal },
    offset_separator = { fg = c.line, bg = c.darker_black },
  }
end
return M
